BEGIN;

-- Migration 010 — Remove FK constraint from audit_log.admin_id
--
-- WHY this migration exists:
--
-- The audit_log table in migration 002 defined a foreign key constraint:
--
--   ALTER TABLE audit_log ADD CONSTRAINT audit_log_admin_id_fkey
--       FOREIGN KEY (admin_id) REFERENCES users(id)
--
-- Note: NO ON DELETE clause (defaults to NO ACTION / RESTRICT).
--
-- When DELETE FROM users fires, PostgreSQL's referential integrity (RI)
-- mechanism checks whether any audit_log row references the user being
-- deleted. It executes:
--
--   SELECT 1 FROM audit_log WHERE admin_id = $1 FOR KEY SHARE
--
-- This row-locking SELECT runs under the privileges of the table owner
-- (valory_app, who owns audit_log). Row-locking operations require UPDATE
-- privilege. However, migration 002 line ~94 deliberately revokes UPDATE on
-- audit_log from valory_app to enforce tamper-evidence (append-only):
--
--   REVOKE UPDATE, DELETE ON audit_log FROM valory_app
--
-- Result: production DELETE /api/v1/users/:id (which ultimately calls
-- Repository.DeleteStudent → DELETE FROM users) fails with:
--
--   ERROR 42501: permission denied for table audit_log
--
-- immediately after RI checks, even though the user has no audit_log rows
-- and no constraint would actually be violated.
--
-- WHY removing the constraint is safe:
--
-- Audit-log integrity does NOT require FK referential integrity. Tamper-
-- evidence is provided entirely by the prev_hash/entry_hash chain — each
-- entry commits the hash of the previous entry, making silent alteration
-- detectable. Admin accounts are NEVER deleted through any application path:
-- they are only deactivated via the API (SetActive(false) → UPDATE users
-- SET is_active=false), so no dangling admin_id can ever occur through the
-- application lifecycle. The audit log remains append-only and tamper-evident.
--
-- The index idx_audit_log_admin_id is retained so queries joining audit_log
-- by admin can still use an efficient index scan.

INSERT INTO schema_migrations (version) VALUES ('010_audit_admin_fk')
    ON CONFLICT (version) DO NOTHING;

-- Drop the FK constraint if it exists. The IF EXISTS guard makes this
-- idempotent: if the constraint has already been dropped by a prior boot,
-- re-applying the migration (e.g., during rolling restarts) does not fail.
-- Note: in migration 002, the constraint is named audit_log_admin_id_fkey
-- (auto-generated by PostgreSQL from the FK syntax). We drop by explicit name.
ALTER TABLE audit_log DROP CONSTRAINT IF EXISTS audit_log_admin_id_fkey;

-- Preserve the index on admin_id for query performance. It was created in
-- migration 002 (line 48) and remains useful for auditing queries that filter
-- by admin. The FK constraint is gone but the index is not.

COMMIT;
